language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: pHc5rs6CV7YxXpTRyFj0MvS4yQsVL2UROZEMHyskFuxqqX3s0ArxYxFeMCRCQ0ObgcMs3sOxdJvl11LeZhyTLUe4Xll5u/UG2CpWCF+vRgXq1ZWRsA1YKMSzbu0bhUuxtVgPvGTtaPT0KpO0WGPUInV6+XNsC6+/hiLdYd12SOYMeacNF3Bx1WtcYTT2QiA1O3vVHoOvy06AmMkZzcLllaZY9fYhIIKMyq2aeweo80m3NhpFMdP8dmRm3Xb/F8z1Uo7NUwe60elnlJjDXlxq55ENymBsq98HZHeci0UHT1gRiO1v7wT/NY1onp9Wtains+TslHhTG9meOv3r3woqREBV8mNw4f1nUHgwvAmLQaTIM4rtQ7Ui2gh03D8HJB+1CILQ13TrcbTAyB6EDSpQUmwojMDvXNNZIsK2d3TgvsVSfREw2ofr/gvbEX1Q4upeao1bxrpOMb5/JdefNB65anInrGjtIaVS/7eo+2c6ZETjsRIiQvQpu5Tu+OC/U6ByWbo4yef9jfA36c5e+vdq5gjbX2NIOqVXvYJJURkR55GymATW5gkMLyXydSAffWTvyGhDRWNlmScpcc7M3TbXikDyNtXUyVBgSW2EYT6hcYDREAL3LXPcHOghkXbRCmMAHnKYGfeE0JhFEuKfBOjzhfw9n2e5qVj5Aw9Cpvs5Bdg=
  app: oflo
  on:
    repo: CDESR/oflo-api-consume
